### ISSUE TITLE
"Sistem belirtilen dosyayı bulamıyor"

### ISSUE THREAD

**Issue by HalBenHB** [DurthVadr/TBD---Tropical-Beach-Diner#21]
Musics in assets folder cannot be found and played.

**Comment by DurthVadr** [comment]
Possible causes:

- maven build doesnt see our src/assets folder as important
- macos windows path name tricks
- maybe we can put the files into target/classes and change the code accordingly

**Comment by HalBenHB** [comment]
assets folder moved from src to root.
